name       : libcdr
version    : 0.1.5
release    : 8
source     :
    - https://dev-www.libreoffice.org/src/libcdr/libcdr-0.1.5.tar.xz : 6ace5c499a8be34ad871e825442ce388614ae2d8675c4381756a7319429e3a48
license    : MPL-2.0
component  : programming
summary    : library and tools for reading and converting Corel DRAW files
description: |
    Libcdr is a library and a set of tools for reading and converting binary files produced by Corel DRAW.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
