name       : libcdr
version    : 0.1.6
release    : 10
source     :
    - https://dev-www.libreoffice.org/src/libcdr/libcdr-0.1.6.tar.xz : 01cd00b04a030977e544433c2d127c997205332cd9b8e35ec0ee17110da7f861
license    : MPL-2.0
component  : programming
summary    : library and tools for reading and converting Corel DRAW files
description: |
    Libcdr is a library and a set of tools for reading and converting binary files produced by Corel DRAW.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
