name       : libcdr
version    : 0.1.7
release    : 12
source     :
    - https://dev-www.libreoffice.org/src/libcdr/libcdr-0.1.7.tar.xz : 5666249d613466b9aa1e987ea4109c04365866e9277d80f6cd9663e86b8ecdd4
license    : MPL-2.0
component  : programming
summary    : library and tools for reading and converting Corel DRAW files
description: |
    Libcdr is a library and a set of tools for reading and converting binary files produced by Corel DRAW.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(lcms2)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
